[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "volleyball-ball-detection"
version = "0.1.0"
description = "Volleyball ball detection using YOLO11"
requires-python = ">=3.11"
dependencies = [
    "ultralytics",
    "labelImg",
    "opencv-python",
    "pandas",
    "matplotlib",
    "ipykernel"
]
